apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    name: mysql-slave
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    name: mysql-master
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-master
  labels:
    app: mysql
    name: mysql-master
spec:
  containers:
  - image: capttofu/mysql_master_kubernetes:latest
    imagePullPolicy: IfNotPresent
    name: mysql-master
    env:
    - name: MYSQL_USER
      value: "mysql"
    - name: MYSQL_PASSWORD
      value: "mysql"
    - name: MYSQL_DATABASE
      value: "sample"
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_REPLICATION_PASSWORD
      value: "repl"
    ports:
    - containerPort: 3306
      hostPort: 3306
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-slave
  labels:
    app: mysql
    name: mysql-slave
spec:
  containers:
  - image: capttofu/mysql_slave_kubernetes:latest
    imagePullPolicy: IfNotPresent
    name: mysql-slave
    env:
    - name: MYSQL_USER
      value: "mysql"
    - name: MYSQL_PASSWORD
      value: "mysql"
    - name: MYSQL_DATABASE
      value: "sample"
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_REPLICATION_PASSWORD
      value: "repl"
    ports:
    - containerPort: 3306
      hostPort: 3306
  restartPolicy: Always
